server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/innovatech_projects

spring.datasource.username=root
spring.datasource.password=

# Propiedades de JPA 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# HIKARICP
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.pool-name=InnovatechHikariPool

# Configuración de kafka 
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Kafka falla rápido sin bloquear
spring.kafka.producer.properties.max.block.ms=1000
spring.kafka.producer.properties.request.timeout.ms=1000
spring.kafka.producer.properties.delivery.timeout.ms=2000

# Mostramos en consola lo que hace HikariCP
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.com.zaxxer.hikari=DEBUG

# Cargar data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#Para que tome historial en http en postman pero es un detalle nomas.
spring.jackson.serialization.fail-on-empty-beans=false

