server.port=8082
spring.application.name=backend-analitico

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5435/innovatech_resources
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#Swagger

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method

# SonarQube
sonar.exclusions=**/model/**,**/*Application.java
sonar.coverage.exclusions=**/model/**,**/*Application.java